language: node_js

before_script:
  npm install serverless

jobs:
  include:
    
    # Unit Test
    # - Runs any unit tests for the API
    - stage: Unit Tests
      script: ./scripts/unit-test.sh
      language: go
      go:
        - 1.14
    # Test Deploy
    # - Deploys the API to the Test environment
    # so that it can be further tested and validated
    # before going into production
    - stage: Deploy Test
      script: ./scripts/deploy-test.sh   
      language: go
      go:
        - 1.14
    
    # Integration Tests
    # - Runs a series of curl commands against
    # the deployed test API endpoint in order to validate
    # functionality
    - stage: Integration Tests       
      script: ./scripts/integration-test.sh
      language: node_js
      node_js:
        - 11
    
    # Production Deployment
    # - Runs the final production deploy to push changes
    # live up to the site 
    - stage: Production Deploy
      script: ./scripts/production-deploy.sh
      language: node_js
      node_js:
        - 11