---
service: tutorialedge-rest-api

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  memorySize: 512

plugins:
  - serverless-prune-plugin
custom:
  # This prunes the storage buckets to ensure that we
  # don't face bucket size issues
  prune:
    automatic: true
    includeLayers: true
    number: 3

# What to include in the deployed package
# for each lambda
package:
  exclude:
  - ./**
  include:
  - ./bin/**

functions:
  # health endpoint which allows us to verify what version
  # of the service is deployed based on Travis Build Number
  health:
    handler: bin/health
    environment:
        TRAVIS_BUILD_NUMBER: ${env:TRAVIS_BUILD_NUMBER}
    events:
    - http:
        path: /
        method: get

  # achievements endpoint which allows a user to retrieve their 
  # achievements on the site
  achievements:
    handler: bin/achievements
    events:
    - http:
        path: /achievements
        method: get
  
  # comments endpoints which allow users to post comments
  # to the site
  comments:
    handler: bin/comments
    environment:
        API_AUDIENCE_ID: ${env:API_AUDIENCE_ID}
        AUTH0_SIGNING_KEY: ${env:AUTH0_SIGNING_KEY}
        DB_USERNAME: ${env:DB_USERNAME}
        DB_PASSWORD: ${env:DB_PASSWORD}
        DB_HOST: ${env:DB_HOST}
        DB_TABLE: ${env:DB_TABLE}
        MAILGUN_API_KEY: ${env:MAILGUN_API_KEY}
    events:
    - http:
        path: /v1/comments
        method: get
        cors: true
    - http:
        path: /v1/comments
        method: post
        cors: true
    - http:
        path: /v1/comments
        method: put
        cors: true
    - http:
        path: /v1/comments
        method: delete
        cors: true
  
  # challenges endpoint allows us to update a user
  # profile and highlight what challenges they have finished
  challenges:
    handler: bin/challenge
    environment:
      API_AUDIENCE_ID: ${env:API_AUDIENCE_ID}
      AUTH0_SIGNING_KEY: ${env:AUTH0_SIGNING_KEY}
      DB_USERNAME: ${env:DB_USERNAME}
      DB_PASSWORD: ${env:DB_PASSWORD}
      DB_HOST: ${env:DB_HOST}
      DB_TABLE: ${env:DB_TABLE}
      MAILGUN_API_KEY: ${env:MAILGUN_API_KEY}
    events:
    - http:
        path: /v1/challenges
        method: get
    - http:
        path: /v1/challenges
        cors: true
        method: post
    - http:
        path: /v1/challenges
        method: put
    - http:
        path: /v1/challenges
        method: delete

  # users endpoints which return the user details for the 
  # profile page. 
  users:
    handler: bin/users
    environment:
        API_AUDIENCE_ID: ${env:API_AUDIENCE_ID}
        AUTH0_SIGNING_KEY: ${env:AUTH0_SIGNING_KEY}
        DB_USERNAME: ${env:DB_USERNAME}
        DB_PASSWORD: ${env:DB_PASSWORD}
        DB_HOST: ${env:DB_HOST}
        DB_TABLE: ${env:DB_TABLE}
        MAILGUN_API_KEY: ${env:MAILGUN_API_KEY}
    events:
    - http:
        path: /v1/user
        method: get
        cors: true
    - http:
        path: /v1/user
        method: post