---
service: tutorialedge-rest-api

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  memorySize: 512

package:
  exclude:
  - ./**
  include:
  - ./code/**
  - ./bin/**

functions:

  health:
    handler: bin/health
    environment:
        TRAVIS_BUILD_NUMBER: ${env:TRAVIS_BUILD_NUMBER}
    events:
    - http:
        path: /
        method: get

  achievements:
    handler: bin/achievements
    events:
    - http:
        path: /achievements
        method: get

  comments:
    handler: bin/comments
    environment:
        API_AUDIENCE_ID: ${env:API_AUDIENCE_ID}
        AUTH0_SIGNING_KEY: ${env:AUTH0_SIGNING_KEY}
        DB_USERNAME: ${env:DB_USERNAME}
        DB_PASSWORD: ${env:DB_PASSWORD}
        DB_HOST: ${env:DB_HOST}
        DB_TABLE: ${env:DB_TABLE}
        MAILGUN_API_KEY: ${env:MAILGUN_API_KEY}
    events:
    - http:
        path: /v1/comments
        method: get
        cors: true
    - http:
        path: /v1/comments
        method: post
        cors: true
    - http:
        path: /v1/comments
        method: put
        cors: true
    - http:
        path: /v1/comments
        method: delete
        cors: true
  
  challenges:
    handler: bin/challenges
    events:
    - http:
        path: /v1/challenges
        method: get
    - http:
        path: /v1/challenges
        method: post
    - http:
        path: /v1/challenges
        method: put
    - http:
        path: /v1/challenges
        method: delete

  users:
    handler: bin/users
    environment:
        API_AUDIENCE_ID: ${env:API_AUDIENCE_ID}
        AUTH0_SIGNING_KEY: ${env:AUTH0_SIGNING_KEY}
        DB_USERNAME: ${env:DB_USERNAME}
        DB_PASSWORD: ${env:DB_PASSWORD}
        DB_HOST: ${env:DB_HOST}
        DB_TABLE: ${env:DB_TABLE}
        MAILGUN_API_KEY: ${env:MAILGUN_API_KEY}
    events:
    - http:
        path: /v1/user
        method: get
        cors: true
    - http:
        path: /v1/user
        method: post
        cors: true
  
  code:
    handler: code/code.lambda_handler
    runtime: python3.6
    timeout: 900
    environment:
        AUTH0_SIGNING_KEY: ${env:AUTH0_SIGNING_KEY}
        GOROOT: "/var/task/go"
    events:
    - http:
        path: /v1/code
        method: post
        cors: true

  posts:
    handler: bin/posts
    environment:
        API_AUDIENCE_ID: ${env:API_AUDIENCE_ID}
        AUTH0_SIGNING_KEY: ${env:AUTH0_SIGNING_KEY}
        DB_USERNAME: ${env:DB_USERNAME}
        DB_PASSWORD: ${env:DB_PASSWORD}
        DB_HOST: ${env:DB_HOST}
        DB_TABLE: ${env:DB_TABLE}
        MAILGUN_API_KEY: ${env:MAILGUN_API_KEY}
    events:
    - http:
        path: /v1/posts
        method: get
    - http:
        path: /v1/posts
        method: post
    - http:
        path: /v1/posts
        method: put
    - http:
        path: /v1/posts
        method: delete